"""add agent intelligence fields

Revision ID: e2bcb0ad2b5c
Revises: 796871a99d87
Create Date: 2026-07-21 06:04:47.158863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bcb0ad2b5c'
down_revision: Union[str, Sequence[str], None] = '796871a99d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('goal', sa.String(length=1000), nullable=True))
    op.add_column('agents', sa.Column('instructions', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'instructions')
    op.drop_column('agents', 'goal')
    op.drop_column('agents', 'role')
    # ### end Alembic commands ###
